/** The service will Provide Videos list to the components
 * 
 */

export class VideoList  {
    Videos:{video_name:string,video_preview:string,video_desc:string,subscribed:boolean}[]=[
        {
          video_name:"this",
          video_preview:"../../assets/n.png",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"../../assets/n.png",
          video_desc:"",
          subscribed:false
        },
        {
          video_name:"this",
          video_preview:"../../assets/n.png",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        {
          video_name:"this",
          video_preview:"sef",
          video_desc:"",
          subscribed:true
        },
        
      ]
}